# Generated by Django 5.2.4 on 2025-09-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='series',
            field=models.CharField(blank=True, db_index=True, help_text="Optional series name, e.g. 'The Lost Heirs of Pfungwe'", max_length=200, null=True),
        ),
    ]
